### ISSUE TITLE
FA: Invalid Date

### ISSUE THREAD

**Issue by mm12** [Earlopain/reverser#114]
FurAffinity requests always return "Error:Invalid Date" 

```
TRANSACTION (0.5ms)  BEGIN
   ↳ app/models/log_event.rb:13:in `add!'
   ArtistUrl Load (0.6ms)  SELECT "artist_urls".* FROM "artist_urls" WHERE "artist_urls"."id" = $1 LIMIT $2  [["id", 99], ["LIMIT", 1]]
   ↳ app/models/log_event.rb:13:in `add!'
   LogEvent Create (7.5ms)  INSERT INTO "log_events" ("loggable_type", "loggable_id", "payload", "created_at", "action") VALUES ($1, $2, $3, $4, $5) RETURNING "id" [["loggable_type", "ArtistUrl"], ["loggable_id", 99], ["payload", "{ ... }"], ["created_at", "2024-01-18 23:25:36.128634"], ["action", 0]] 
   ↳ app/models/log_event.rb:13:in `add!'
   TRANSACTION (3.1ms)  COMMIT
   ↳ app/models/log_event.rb:13:in `add!'
 invalid date
[downstream error info]
Retrying ScrapeArtistUrlJob (Job ID: [id] after 1 attempts in 3 seconds, due to a Date::Error (invalid date).
```

**Comment by faucetlol** [comment]
See this comment in the config file:
https://github.com/Earlopain/reverser/blob/25803af694d3420ec49726ccc66bda727f577fa6/config/reverser.yml#L43
