### ISSUE TITLE
Exception when trying to create new artists

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#60]
Just updated from 71359d85e0e103be3461ecdc887dce2c6e4cd934 to 10511a45300baa0a86cacf15667d3b0805721acf and now get this exception when opening the new artist page.

```
RuntimeError exception raised
In order to use respond_with, first you need to declare the formats your controller responds to in the class level.

Request
{
  "params": {
    "controller": "artists",
    "action": "new"
  },
  "referrer": "http://localhost:9000/",
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
}

Stacktrace
app/controllers/artists_controller.rb:6:in `new'
app/controllers/application_controller.rb:26:in `with_time_zone'
```

**Comment by Earlopain** [comment]
Even stupid tests would have prevented this, but who got time for that?
